services:
  graphql-server:
    container_name: graphql-server
    build:
      context: .
      target: ${TARGET:-prod}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider --header=\"apollo-require-preflight: true\" http://localhost:4000/graphql?query=%7B__typename%7D || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 5
    ports:
      - 4000:4000