type Query {
  sum(nums: [Float!]!): Float!

  subtract(nums: [Float!]!): Float!

  multiply(nums: [Float!]!): Float!

  divide(nums: [Float!]!): Float!
  """
  Nested calculations using OperationInput
  """
  nestedCalc(operation: OperationInput!): Float!
}

input ValueInput {
  numbers: [Float!]
  operation: OperationInput
}

input OperationInput {
  type: OperationType!
  values: [ValueInput!]!
}

enum OperationType {
  SUM
  SUBTRACT
  MULTIPLY
  DIVIDE
}
